### ISSUE TITLE
Demo APK does not seem to work

### ISSUE THREAD

**Issue by Nawick** [nitrico/MapViewPager#2] opened 2016-02-01 08:30 UTC
Hi,

Tried to install demo APK on Nexus 5 [4.4.4](I know ! :)) and Moto G [5.1].
Crash at startup with :

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/tools/fd/runtime/AppInfo;
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.AppInfo" >on path: DexPathList[[zip file "/data/app/com.github.nitrico.mvp-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
> Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by nitrico** [comment] 2016-02-01 12:42
Oops, you're right. It was caused by the _Instant run_ thing (Android Studio 2.0). 
It should be fixed now. Thanks.

**Comment by nitrico** [comment] 2016-02-02 13:09
Fixed on 292b7f9443eb028293e847b5b7e9e1624ab0bb10

**Comment by nitrico** [comment] 2016-02-02 13:09
Fixed on 292b7f9443eb028293e847b5b7e9e1624ab0bb10

**Closed as completed by nitrico** 2016-02-02 13:09 UTC
